---
policy:
  description: "The name of the policy"
  required: true

nodes_installed:
  description: "The number of nodes with an installed OS"
  default: 0
  required: true

nodes_finished:
  description: "The number of nodes completed"
  default: 0
  required: true

