---
policy:
  description: "The name of the policy"
  required: true

nodes_booting:
  description: "The number of nodes booting"
  default: 0
  required: true

nodes_finished:
  description: "The number of nodes completed"
  default: 0
  required: true
  
nodes_registered:
  decription: "The number of nodes register"
  default: 0
  required: true
