#!/usr/bin/env ruby
require 'json'
require 'net/http'
require 'uri'
require 'rest_client'

input = STDIN.read
STDIN.close_read

input = JSON.parse(input)
config = input['hook']['configuration']
username = input['node']['facts']['user']
ipaddress = input['node']['facts']['ipaddress_eno16777984']
policy = input['policy']['name']

if config['counter'].to_i.to_s != config['counter'].to_s
  puts({ 'error' => "Hook configuration `counter` must be an integer (was: #{config['counter']})" }.to_json)
  exit 1
elsif policy != config['policy']
  output = {'output' => "No match for policy '#{policy}' found in hook; skipping"}
else
  policy_counter = config['counter'].to_i
  next_policy_counter = policy_counter + 1
  # This could just as easily call an external system to retrieve the node's
  # hostname0.

  api_url = "http://commander.bellevuelab.isus.emc.com/hubot/vm/complete"
  # req = Net::HTTP::Post.new uri.path
  api_payload = {"user" => username, "ipaddr" => ipaddress}

  # res = Net::HTTP.start(uri.host, uri.port) do |http|
  #   http.request req
  # end

  # Send packet to hubot
  req = RestClient::Request.execute( method: :post, url: api_url, verify_ssl: false, payload: api_payload, headers: { content_type: 'application/json'})

  output = {
      'hook' => {
          'configuration' => {
              'update' => {
                  'counter' => next_policy_counter
              }
          }
      }
  }
end

puts output.to_json
